---
- name: Configure acl name
  hosts: r3
  gather_facts: false
  tasks:
    - name: Configure acl
      cisco.ios.ios_config:
        lines:
          - 10 permit ip host 192.168.2.1 any
          - 20 permit ip host 192.168.2.2 any
          - 30 permit ip host 192.168.2.3 any
          - 40 permit ip host 192.168.2.4 any 
          - 50 permit ip host 192.168.2.5 any                      
        parents: ip access-list extended demo_acl
        before: no ip access-list extended demo_acl
        match: exact
      register: acl_config

    - name: Print ACL Config
      ansible.builtin.debug:
        msg: "{{ acl_config }}"

    - name: Execute show ip access list
      cisco.ios.ios_command:
        commands: show ip access-list
      register: acl_cmd

    - name: Print show ip access list
      ansible.builtin.debug:
        msg: "{{ acl_cmd.stdout_lines }}"  
