all:
  children:
    routers:
      vars:
        ansible_become: 'true'
        ansible_become_method: enable
        ansible_become_password: admin
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_password: admin
        ansible_user: admin
      children:
        vios_group:
          hosts:
            r101:
              ansible_host: 192.168.0.101
