---
- name: Until demo
  hosts: r2
  gather_facts: false
  tasks:
    - name: Gather Interfaces
      cisco.ios.ios_interfaces:
        state: gathered
      register: intf_config
      until: intf_config.gathered[1]['enabled'] == true
      retries: 5
      delay: 10

    - name: Print intf conf
      ansible.builtin.debug:
        msg: "{{ intf_config.gathered[1]['enabled'] }}"

 